### ISSUE TITLE
What Kafka version is supported exactly? 0.8 doesn't seem to work.

### ISSUE THREAD

**Issue by yankov** [bpot/poseidon#33]
I tried 0.8.0-beta1, 0.8.0 and 0.8.1 Kafkas, but none of them seem to work with Poseidon. Same error message:

```
[2014-04-21 14:27:45,526] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
kafka.common.KafkaException: Wrong request type 768
    at kafka.api.RequestKeys$.deserializerForKey(RequestKeys.scala:53)
    at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:49)
    at kafka.network.Processor.read(SocketServer.scala:345)
    at kafka.network.Processor.run(SocketServer.scala:245)
    at java.lang.Thread.run(Thread.java:744)
```

Here is a snippet I use to send a message

``` ruby
require 'poseidon'

producer = Poseidon::Producer.new(["localhost:9092"], "my_test_producer")
messages = []
topic = "test"
messages << Poseidon::MessageToSend.new(topic, "Hello from Ruby producer")
producer.send_messages(messages)
```

**Comment by divyesh2506** [comment]
Hi, I am facing a similar solution with ruby 2.2.2 and kafka 0.8.2
Could please elaborate how you solved the problem or what was the cause of the problem.
